config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'home#splash', as: :unauthenticated_root
    end
    put '/phones' => 'users/users#update', as: 'update_user'
  end

  get '/events', to: 'budget_events#index', as: 'events'
  post '/events', to: 'budget_events#create', as: 'create_event'
  delete '/events/:id', to: 'budget_events#destroy', as: 'destroy_event'
  get '/home', to: 'home#index'
  get '/begin', to: 'institutions#begin'
  get '/step', to: 'institutions#step'
  post '/authorize', to: 'institutions#authorize'
  post '/mfa', to: 'institutions#mfa'
  post '/institutions/:id', to: 'institutions#update', as: 'update_institution'
  post '/hooks', to: 'hooks#hook'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, except: :splash

  def index
    @institutions = current_user.institutions.valid_tokens
  end

  def splash
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
.row
  .large-8.columns.large-centered.panel
    Welcome to WeSave.  This app is very much in limited Alpha.  I take all precautions to safegaurd your banking information.  I never store you personal passwords, pins or usernames.  I use that information to get a token from an api, I store that token.
.row
  - unless current_user.phone_number
    .large-6.columns.large-centered
      = form_for :user, url: update_user_path, method: :put do |f|
        = f.text_field :phone_number, placeholder: "your phone number"
        .center
          = f.submit "submit", class: "button success radius tiny"

  - if current_user.phone_number 
    - @institutions.each do |institution|
      .border
        %h3.center
          = institution.name
        - if institution && ! institution.has_primary?
          Please select this institutions 'account of concern' it should be your primary checking account.
          = form_for :institution, url: update_institution_path(institution)  do |form|
            - institution.accounts.each do |account|
              .center
                = form.radio_button 'institutional_account_id', account.institutional_account_id
                = account.name
            .center
              = form.submit "set account", class: "button success tiny radius center"
        - if institution.account_of_concern
          .center
            primary account is:
            = institution.account_of_concern
          .center
            = link_to "Add Budget Details", events_path, class: "button success radius small center"
    - if @institutions.empty?
      %h4.center
        = link_to "Add an account.", begin_path, class: "button radius success large"