config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'home#splash', as: :unauthenticated_root
    end
    put '/phones' => 'users/users#update', as: 'update_user'
  end

  get '/events', to: 'budget_events#index', as: 'events'
  post '/events', to: 'budget_events#create', as: 'create_event'
  delete '/events/:id', to: 'budget_events#destroy', as: 'destroy_event'
  get '/home', to: 'home#index'
  get '/begin', to: 'institutions#begin'
  get '/step', to: 'institutions#step'
  post '/authorize', to: 'institutions#authorize'
  post '/mfa', to: 'institutions#mfa'
  post '/institutions/:id', to: 'institutions#update', as: 'update_institution'
  post '/hooks', to: 'hooks#hook'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "wesave.co" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="row">
      <div class="large-6 large-centered columns">
        <% flash.each do |key, value| %>
          <div class="alert alert-box rounded"><%= value %></div>
        <% end %>
      </div>
    </div>
    <%= yield %>
    <% if current_user %>
      <div class="center">
        <b>Signed In as <%= current_user.email %></b>
        <%= link_to "sign out", destroy_user_session_path, method: :delete, class: "button info radius tiny" %>
        <%= link_to "home", home_path, class: "button info radius tiny" %>
      </div>
    <% end %>
    <%= javascript_include_tag "application" %>
  </body>
</html>